(function(z){
var SK=function(a,b,c){b="new"===(b||a.jd);return c?(a=a.d.u.v().get(z.U.op),b?-1:-a):a.Uk+(b?-1:1)};var TK=function(a){z.Dv.call(this,a);this.Uk=0;this.jd="new"};var UK=function(a,b){a.RW=b};var VK=function(a){return a.get(a.k.wp)};
var WK=function(a){return(0,z.P)('\x3cdiv class\x3d"fyre '+(a.je?"fyre-liveblog ":"")+(a.$g?"fyre-livechat ":"")+(a.qT?"fyre-bootstrap ":"")+(a.ke?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Va?"fyre-avatar-disabled":"")+'"\x3e'+(a.fv?z.lm(z.Ks(a)):"")+(0,z.P)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Va?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.Yn?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var XK=function(a){return(0,z.P)('\x3ca href\x3d"'+z.Q(z.R(a.Ea))+'" title\x3d"'+z.Q(a.Z)+'" data-id\x3d"'+z.Q(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.Q(a.ZS)+'"\x3e\x3cimg src\x3d"'+z.Q(z.R(a.xd))+'" alt\x3d"'+z.Q(a.Z)+'" onerror\x3d"javascript:this.src\x3d\''+z.Q(z.Fm(a.Zb))+"';\" /\x3e\x3c/a\x3e")};
var YK=function(a){return(0,z.P)(z.Vq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.O(a.j.zN)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(a.j.Ex)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(a.j.Fo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(a.j.Fx)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var ZK=function(a){return(0,z.P)('\x3cdiv class\x3d"tooltip"\x3e'+z.O(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var $K=function(){};var aL=function(a){z.Gf.call(this,a);this.rJ=new z.Pe({url:[z.v.K.OW,"stats"].join("/"),method:"POST",with_credentials:!1});this.Ds=[];this.yb=z.t.setInterval((0,z.r)(this.vy,this),5E3)};var bL=function(a){return z.Pa(a,function(a){return a.rate?Math.random()<a.rate:!0})};
var cL=function(a){var b={},c=z.Pa(a,function(a){if("counter"!==a.type)return!0;a.metric in b?b[a.metric].value+=a.value:b[a.metric]=a;return!1});z.x(b,function(a){c.push(a)});return c};var dL=function(a){this.cG=!1;this.so=[];this.yb=null;z.Gf.call(this,a)};var eL=function(a,b){z.Hj.call(this,b,a)};var fL=function(a,b){z.KF.call(this,a,b)};
var gL=function(a,b){var c=a.d.Bb;c.oh[4]&&(z.Ty(c,4,(0,z.r)(function(a){b.e(a,"threadBreakout",this.tr)},a)),z.Vy(c,4,(0,z.r)(function(a){b.Za(a,"threadBreakout",this.tr)})))};var hL=function(a,b){var c=[a.fm,a.Vy];a.tg&&c.push(a.tg);a.Zs&&c.push(a.Zs);a.Wy&&c.push(a.Wy);z.w(c,function(a){z.No(a,"fyre-stream-sort-selected")});z.Lo(b,"fyre-stream-sort-selected")};var iL=function(a,b){z.KF.call(this,a,b)};
var jL=function(a,b){z.wx.call(this,a,b);this.Zg=!1;this.iI=!!this.G.M.fG;this.Ga=new z.Ex;this.Ga.qc(this);this.Vt="archiveShowMore"};var kL=function(a,b){z.HF.call(this,a,b)};var lL=function(a,b,c){z.Yt.call(this,a,b,c);this.pz=b||"";this.qg(ZK(this.s()))};var mL=function(a,b,c){z.St.call(this,a,b||3,c)};var nL=function(a,b){z.T.call(this,b);this.m=a};var oL=function(a,b){z.T.call(this,b);this.cc=a};var pL=function(a,b){oL.call(this,a,b)};
var qL=function(){var a=z.t.window,b=z.t.document;function c(){var a=A.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){A.uW||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(A,g)}function f(a){var b;if(a.GO)return a;if(A.tW&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.GO=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.kT&&a.kT("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var A={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.tW,shivMethods:!1!==g.uW,type:"default",shivDocument:f};f(b)};var rL=function(a,b){z.SF.call(this,a,b);a.M.zO||qL();var c=a.u.Mb(),d=a.u.v();this.hg=new z.IF(a,c,a.Hl.Da,d.$g()||z.dg);this.D(this.hg);a.M.Va||(this.tn=new pL(c),this.D(this.tn));this.Ar=new z.GF;this.D(this.Ar)};var sL=function(a){var b=z.E.cb();return!a.B.je()||b};var tL=function(a){z.bz.call(this,a);this.Km=1};var uL=function(a){z.Ns.call(this,a);z.gv(a.u);this.Qb=new rL(a);this.Hq.start();this.vl(this.Qb);z.Rs(this)};
var vL=function(a,b){this.FC=eL;this.mJ=uL;z.X.Jo(b.strings||{});z.wl.call(this,a,b)};var wL=function(a){a.jk&&(a.jk.p(),delete a.jk)};z.u(TK,z.Dv);z.e=TK.prototype;z.e.hl=z.l(58);z.e.eF=z.l(60);z.e.fF=z.l(59);z.e.eF=z.K(60,function(a){this.Ja||(this.oo[a]=!1,z.Ev(this,a,function(a){a.N(a.xa.Jm)}))});
z.e.fF=z.K(59,function(a,b){if(!this.Ja){var c=this.d.u.v(),d=z.Du(a,b),f=c.get(z.U.tt);c.set(z.U.op,d.DU);z.x(d.ab,(0,z.r)(this.d.R.N,this.d.R,"bootstrap_author_received"));d.content=z.kj(d.content,function(a,b){return!z.Ua(f,b)});z.x(d.content,function(a){z.y(d.content,z.Gv(this,a))},this);z.y(this.Cc,z.jj(d.content,z.Bb(a)));this.Xd(a,d.content);z.Ev(this,a,function(b){b.N(b.xa.zk,{Hd:a});b.set(b.k.cf,!0)})}});
z.e.hl=z.K(58,function(a,b){this.Uk=a;this.jd=b||this.jd;var c=this.Id[a]=new z.Av;z.Xu.C();var d=this.d.u.v(),f=(0,z.r)(this.fF,this,a),g=(0,z.r)(this.eF,this,a),h=this.d.M.Pm,d=d.get(z.U.Hc),h=z.v.yu(d,h)+String(a)+".json";z.Yu(0,h,f,g);return c});z.nG.prototype.hl=z.K(57,function(a,b){this.Ik||(this.Ik=new TK(this.G));var c=this.Ik,d=SK(c,a,b);return c.hl(d,a)});z.Xu.prototype.Qh=z.K(49,function(a,b,c){a=z.xa("%s%scollection/%s/hot/",z.v.K.yd,z.v.$e,a.na);(new z.Pe({url:a,wa:b,sa:c})).send()});
z.Uv.prototype.Qh=z.K(48,function(a){var b={na:this.d.u.v().id},c=z.Xu.C().Qh;z.Vv(this,c,b,a);return a});z.nG.prototype.Qh=z.K(47,function(){z.$v(this);this.Di=new z.Uv(this.G,void 0);var a=new z.Av;this.Di.Qh(a);return a});z.Xu.prototype.Mh=z.K(46,function(a,b,c){a=z.xa("%s%scollection/%s/top/%s/",z.v.K.yd,z.v.$e,a.na,a.tN);(new z.Pe({url:a,wa:b,sa:c})).send({format:"stream"})});z.Uv.prototype.Mh=z.K(45,function(a,b){var c={na:this.d.u.v().id,tN:a},d=z.Xu.C().Mh;z.Vv(this,d,c,b);return b});
z.nG.prototype.Mh=z.K(44,function(a){z.$v(this);this.Di=new z.Uv(this.G,void 0);var b=new z.Av;this.Di.Mh(a,b);return b});z.T.prototype.rG=z.K(43,function(){return this.aa});z.Ej.prototype.Yn=z.K(42,function(){return this.get(this.k.np)});z.u($K,z.Cl);z.da($K);var xL={RX:"attachmentDelegate"};z.y(xL,z.BG);$K.prototype.Vn=function(a){var b=$K.b.Vn.call(this,a),c=a.attachmentDelegate;c&&(b.BN=c);b.yx=a[xL.oL]||null;return b};z.u(aL,z.Gf);aL.prototype.send=function(a){this.Ds=this.Ds.concat(a)};aL.prototype.vy=function(){var a=cL(this.Ds),a=bL(a);a.length&&this.rJ.send(z.kd(a),{"Content-Type":"application/json"});this.Ds=[]};aL.prototype.p=function(){(0,window.clearInterval)(this.yb);this.rJ=null;aL.b.p.call(this)};z.u(dL,z.Gf);dL.prototype.NT=function(a){this.yb||(this.yb=z.t.setInterval((0,z.r)(this.FP,this),5E3));this.so=this.so.concat(a)};
dL.prototype.FP=function(){this.so.length&&(this.cG||(z.tc("//platform.twitter.com/impressions.js"),this.cG=!0),z.t.twttr=function(){var a=z.t.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.t.twttr.impressions.ready((0,z.r)(function(a){a.impressions.logTweets(this.so,{partner:"livefyre"});this.so=[]},this)))};dL.prototype.p=function(){(0,window.clearInterval)(this.yb);dL.b.p.call(this)};z.u(eL,z.Hj);eL.prototype.Gy=function(a){this.yi=new z.Tu(this);this.gu=new z.Lq(this,a);this.Jc=new z.Ai(this);this.bb=new z.pv(this,a);this.Hl=new z.wv(this);this.u=new z.ev(this,a);this.Kb=new z.nG(this,a);new z.rf;this.Mo=new z.kw(this,a);this.PW=new aL(this);this.kX=new dL(this);this.Bb=new z.Jy(this)};z.u(fL,z.KF);z.e=fL.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.tx=b.v().je();a.AU=!z.E.get(z.E.k.Sd);a.Al=b.Al(z.E.id);a.CO=2===c.get(z.U.Si);a.BO=3===c.get(z.U.Si);a.j={GT:z.X.get(z.X.g.Jt),JT:z.X.get(z.X.g.Kt),XS:z.X.get(z.X.g.GA),Ex:z.X.get(z.X.g.Ip),Fx:z.X.get(z.X.g.Jp),Fo:z.X.get(z.X.g.KB),Wo:z.X.get(z.X.g.Mp),eX:z.X.get(z.X.g.bC)};return a};
z.e.H=function(a){fL.b.H.call(this,a);a=this.c;var b;b=this.s();var c=z.P,d=z.Vq(b),f;f=b.tx?(0,z.P)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.AU?b.Al?z.O(b.j.JT):z.O(b.j.GT):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(b.j.Ex)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Fo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(b.j.Fx)+"\x3c/a\x3e"+(b.CO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Fo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.O(b.j.eX)+"\x3c/a\x3e":"")+(b.BO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.Fo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.O(b.j.XS)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.gl=this.n("fyre-follow-conversation");this.Zs=this.n("fyre-stream-sort-hot-threads")||
null;this.Wy=this.n("fyre-stream-sort-top-comments")||null;this.tg=this.n("fyre-stream-sort-back");this.fm=this.n("fyre-stream-sort-newest");this.Vy=this.n("fyre-stream-sort-oldest");this.nI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Dd()};z.e.l=function(){fL.b.l.call(this);var a=this.q();z.E.on(z.E.xa.Mf,this.Pn,this);a.e(this.c,"click",this.hb);z.w([3,4,5],function(b){z.LF(this,a,b)},this);gL(this,a)};
z.e.hb=function(a){a.preventDefault();a=a.target;if(!z.Ro(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.tg)if(a===this.gl)this.dF();else switch(hL(this,a),this.em(),a){case this.Zs:this.RD();break;case this.Wy:this.dispatchEvent({type:"sortTopComments",Ub:(0,z.r)(this.Dd,this)});break;case this.fm:this.gn("new");break;case this.Vy:this.gn("old")}};z.e.vi=function(a,b){a&&this.Hy(b);z.Mn(this.nI,"display",a?"none":"block");z.Mn(this.tg,"display",a?"block":"none")};
z.e.Hy=function(a){var b=this.fm,c=this.gn,d=z.X.get(z.X.g.ut);4===a&&(b=this.Zs,c=this.RD,d=z.X.get(z.X.g.AJ));this.tg.innerHTML=d;this.q().vf(this.tg,"click",(0,z.r)(function(a){a.stopPropagation();this.vi(!1);hL(this,b);c.apply(this)},this))};z.e.Mn=function(a){a.stopPropagation();this.vi(!1);hL(this,this.fm);this.gn()};z.e.tr=function(a){var b=a.Ub;z.y(a,{Ub:(0,z.r)(function(){b();this.vi(!0,4)},this)})};
z.e.gn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Ub:(0,z.r)(this.Dd,this)})};z.e.RD=function(){this.dispatchEvent({type:"sortHotThreads",Ub:(0,z.r)(this.Dd,this)})};z.e.dF=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.Al(z.E.get(b.W)),a.sj(!b),a=b?z.X.get(z.X.g.Jt):z.X.get(z.X.g.Kt),this.gl.innerHTML=a):z.Rh(this.d.Jc,(0,z.r)(this.dF,this))};
z.e.Pn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.je()||z.E.get(c.Sd);this.gl&&(b?z.S(this.gl,!1):(a=a.Al(z.E.id)?z.X.get(z.X.g.Kt):z.X.get(z.X.g.Jt),this.gl.innerHTML=a,z.S(this.gl,!0)))};z.e.h=function(){fL.b.h.call(this);z.E.off(null,null,this)};z.u(iL,fL);iL.prototype.H=function(a){this.c=a;z.Yl(a,YK,this.s());this.fm=this.n("fyre-stream-sort-newest");this.Vy=this.n("fyre-stream-sort-oldest");this.nI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Dd()};iL.prototype.gn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.RW.stream,direction:a,Ub:(0,z.r)(this.Dd,this)})};
iL.prototype.s=function(){return{j:{zN:z.X.get(z.X.g.vJ),Ex:z.X.get(z.X.g.Ip),Fx:z.X.get(z.X.g.Jp),Fo:z.X.get(z.X.g.KB),Wo:z.X.get(z.X.g.Mp)}}};z.u(jL,z.wx);z.e=jL.prototype;z.e.Xm=function(a){this.clear();z.S(this.c,!0);this.jd=a};z.e.clear=function(){this.gd.Kd();this.ub={};this.zj=[];for(this.ph=this.Lk=null;this.ma&&0!=this.ma.length;)this.wo(0).p()};z.e.H=function(a){jL.b.H.call(this,a);z.Yl(this.c,z.Wq,this.s());this.ck=this.n("fyre-stream-content");this.wi=this.n("fyre-stream-more");this.Ga.S(this.wi);z.S(this.wi,!1)};z.e.h=function(){this.Ga&&this.Ga.p();this.Ga=null;jL.b.h.call(this)};
z.e.l=function(){jL.b.l.call(this);this.q().e(this.Ga,"showMore",this.Fw)};z.e.Hv=function(){return this.G.M.fG};z.e.s=function(){return{Rc:z.v.K.mb,Zu:!!this.Ga,j:{Ny:z.X.get(z.X.g.wJ)}}};z.e.Gw=function(){this.Ga.Us();this.Zg=!0};z.e.Xx=function(){this.dispatchEvent({type:this.Vt,direction:this.jd,target:this,sX:this.Zg&&this.iI,Ub:(0,z.r)(this.Gw,this),rj:(0,z.r)(this.CF,this)});this.Zg&&(this.iI=!1)};z.e.dy=function(a){this.Zg||jL.b.dy.call(this,a)};
z.e.Lo=function(){var a=this.G.Kb.Ik,b=this.jd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.op),c=!b&&a.Uk>-c;b&&-1>a.Uk||c?this.Ga.show():this.Ga.pb()};z.e.start=function(){this.Zg||this.Xx()};z.u(kL,z.HF);var yL=z.X.g,zL={};zL.comment=[yL.Em,yL.Nf,yL.tm];zL.liveblog=[yL.QL,yL.cL,yL.MA];kL.prototype.BE=function(a){function b(a){return z.Ha(a,"%s")?a:"%s "+a}var c=this.m.je()?"liveblog":"comment",c=zL[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.FF[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.xa(c,a)};z.u(lL,z.Yt);lL.prototype.Oo=200;lL.prototype.Sh=function(){return new mL(this.Ic)};lL.prototype.s=function(){var a={};a.message=this.pz;return a};z.u(mL,z.St);mL.prototype.Nc=function(a,b,c){var d=z.lo(this.element),d=new z.Bh(d.width,d.height+25);b=z.Nt(this.element,this.Fh,a,b,d,c,9);z.Sn(a.lastChild,0);b&&(d=new z.Bh(0,-5),z.Nt(this.element,2,a,1,d,c,5),z.Sn(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.u(nL,z.T);z.e=nL.prototype;z.e.r=function(){this.c=z.am(XK,this.s())};z.e.l=function(){nL.b.l.call(this);this.Ta=new lL(this.c,this.m.get("displayName"));this.q().e(this.c,"click",this.hb)};z.e.h=function(){nL.b.h.call(this);this.Ta&&this.Ta.p()};z.e.s=function(){var a=z.Wd,b={};b.xd=this.m.get(a.wb);b.Zb=this.m.get(a.qk);b.Z=this.m.get(a.ua);b.id=this.m.id;b.ZS=this.m.id.replace(/[@.]/g,"-");b.Ea=this.m.get(a.Wb);return b};
z.e.hb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};z.u(oL,z.T);z.e=oL.prototype;z.e.QA=10;z.e.h=function(){oL.b.h.call(this);delete this.cc};z.e.Q=function(){oL.b.Q.call(this);this.cc.off(null,null,this)};z.e.OE=function(a){a=new nL(a);var b=this.Mc();if(b===this.QA){var c=this.wo(b-1);c&&(c.p(),b--)}0<b?this.ye(a,0,!0):this.D(a,!0)};z.e.cS=function(a){var b;this.Tc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Yh=function(){this.cc.on(this.cc.xa.st,this.OE,this);this.cc.on(this.cc.xa.St,this.cS,this);var a=this.cc.qb.reverse().slice(0,this.QA);z.w(a,this.OE,this)};z.u(pL,oL);z.u(rL,z.SF);
rL.prototype.GH=function(a,b){if(!this.Ja){this.B=b;var c=b.get(z.U.yh),d=b.get(z.U.Ud);this.mt=new z.PF(c,d,a.M.Va);this.D(this.mt);this.rq=new kL(a.u.v());this.D(this.rq);this.fs=null;b.Yn()&&(this.ru=new iL(a),this.D(this.ru),this.Jk=new jL(a),this.D(this.Jk),UK(this.ru,{stream:this.Jk}));this.mh=new fL(a);this.D(this.mh);this.Xr((0,z.r)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.Ee,!0)},this));b.get(z.U.zm)&&!z.dg&&VK(this.B)&&(this.B.$g()||this.B.je()||this.iw())}};
rL.prototype.s=function(){var a=!this.d.M.hq&&!z.v.Xu&&!this.d.M.ND;return{LI:z.v.K.qz,MI:(0,window.encodeURIComponent)(String(window.location.href)),Va:this.d.M.Va,$g:this.B.$g(),je:this.B.je(),ke:z.dg,fv:a,qT:this.d.M.hq,Yn:this.B.Yn()}};z.Kx={NX:"fyre-archive-stream",OX:"fyre-archive-stream-header",C0:"fyre-top-content-stream",V0:"fyre-widget",zm:"fyre-featured-content-wrapper"};z.y(z.Kx,z.DJ);z.e=rL.prototype;
z.e.r=function(){this.c=z.am(WK,this.s());var a=this.B.get(z.U.Si);if(1!==a){var b=this.d.Bb,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.Ky(b,a,c,this)}this.Ar.S(this.n(z.Kx.OK));this.Jk&&(b=this.n("fyre-archive-stream-header"),this.ru.S(b),this.Jk.S(this.n("fyre-archive-stream")));this.Gh(1);this.Ee=this.n(z.Kx.wh);b=sL(this);z.S(this.Ee,b)};
z.e.l=function(){rL.b.l.call(this);var a=this.$b;this.aa&&a&&a.S(this.Ee,!0);this.d.R.Yo("stream_data_received",this.$Q,this);this.q().e(this,"request_content_context",this.zQ).e(this,"request_content_reply",this.fS);this.Jk&&this.Jk.start()};z.e.Yh=function(){this.tn&&this.tn.Yh();this.hg.Yh()};z.e.$Q=function(){var a=this.B,b=a.get(z.U.tk);z.sh||b||(b=(0,z.r)(function(){this.fs=new z.AL(this.d,a.get(z.U.Ud));this.D(this.fs,!0)},this),z.tc(z.v.K.mb+z.v.xf.fs,null,null,b))};
z.e.iw=function(){var a=new z.yE(this.rG,this);a.hH=(0,z.r)(this.QV,this);var b=(0,z.r)(function(){a.start(0,2E3)},this);z.tc(z.v.K.mb+z.v.xf.iP,null,null,b)};z.e.QV=function(){var a=this.n("fyre-featured-content-wrapper");this.sv=new z.TJ(this.d);this.D(this.sv);this.sv.S(a);this.sv.Yg()};z.e.Xr=function(a){if(!this.d.M.readOnly){var b=this.d.u.v();z.Fw(z.Cw.C(),"main",a,{G:this.d,oi:"new"},b);z.E.on(z.E.ic(z.E.k.W),this.Uc,this)}};z.e.Uc=function(){var a=sL(this);z.S(this.Ee,a)};
z.e.Xh=function(){0<z.Co(this,this.$b)&&(this.removeChild(this.$b),this.$b.p());this.Xr((0,z.r)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.Ee,!0);z.S(this.Ee,!0)},this))};z.e.Wg=function(a){null!=a&&(this.d.Bb.ml(1),(0,window.setTimeout)((0,z.r)(function(){this.Ja||z.TF(this,a)},this),3E3))};z.e.zQ=function(a){z.TF(this,a.Pk)};z.e.fS=function(a){z.TF(this,a.Pk,function(a){z.Bw(a.Jb)})};
z.e.h=function(){rL.b.h.call(this);z.E.off(z.E.ic(z.E.k.W),this.Uc,this);this.B&&(this.B.off(null,null,this),this.B=null)};z.u(tL,z.bz);z.e=tL.prototype;z.e.ge=function(a,b){tL.b.ge.call(this,a,b);a.e(b,"repliesExpanded",this.aF);a.e(b,"sortHotThreads",this.pS);a.e(b,"sortOrderChanged",this.FF);a.e(b,"sortTopComments",this.qS);a.e(b,"archiveShowMore",this.jQ);a.e(b,"archiveSortOrderChanged",this.kQ)};
z.e.jQ=function(a){var b=a.Ub||z.n,c=(0,z.r)(this.Je,this,a.target),d=this.d.Kb;a=a.sX;d.Ik||(d.Ik=new TK(d.G));d=d.Ik;a=a?d.Uk:SK(d);var f=d.Nd[a];f&&(d.Uk=a);if(f)b(),c(f);else{d=this.d.Kb.hl();a=d.k.cf;if(d.get(a))b();else d.on(d.ic(a),b,this);z.cz(this,d,c)}};z.e.dw=function(a,b){var c=2===b.Zc,d=1!==b.Zc;switch(b.type){case 0:var f=this.d.u.v(),f=z.wk(b,f),g=f.get(z.Jk),g=this.d.u.ab().get(g);f.set(z.xk,g);a.ww(f,c,d)}};
z.e.xF=function(a){if(1!==this.Km){var b=this.IW.mh;b.vi(!1);hL(b,b.fm);z.y(a,{direction:"new",Ub:z.n});this.FF(a)}};z.e.kQ=function(a){z.dz(this);a.stream.Xm(a.direction);var b=this.d.Kb.hl(a.direction,!0),c=(0,z.r)(function(b){a.Ub();this.Je(a.stream,b)},this);z.cz(this,b,c,a.rj)};z.e.FF=function(a){this.d.M.xl=null;var b=z.fz(this,1);z.$v(this.d.Kb);b.Xm(a.direction);var c=z.Zv(this.d.Kb,a.direction),d=(0,z.r)(function(c){a.Ub();this.Je(b,c)},this);z.cz(this,c,d,a.rj)};
z.e.qS=function(a){var b=z.fz(this,3),c=this.d.Kb.Mh("likes");z.cz(this,c,(0,z.r)(function(c){a.Ub();z.hb(c)?z.vx(b):this.Je(b,c)},this))};z.e.pS=function(a){var b=z.fz(this,4),c=this.d.Kb.Qh();z.cz(this,c,(0,z.r)(function(c){a.Ub();z.hb(c)?z.vx(b):this.Je(b,c)},this))};z.u(uL,z.Ns);z.e=uL.prototype;z.e.c=null;z.e.h=function(){uL.b.h.call(this);this.at.p();this.hD.p();this.Qb.aa&&this.Qb.p();this.Lf&&this.Lf.p();delete this.Lf};z.e.vl=function(a){uL.b.vl.call(this,a);this.at=new tL(this.d);this.at.handle(a);this.hD=new z.Zy(this.d);this.hD.handle(a)};z.e.cz=function(){this.d.yi.stop()};z.e.QW=function(){this.d.Hl.stop()};z.e.$j=function(){this.d.yi.start()};z.e.MW=function(){this.d.Hl.start()};
z.e.pa=function(){this.Lf&&this.Lf.p();this.Qb.pa(this.c);if("object"===typeof window.Livefyre&&window.Livefyre.lN)z.Ss(this);else{var a=z.Ps(this);this.Qb.Wg(a)}this.d.R.N("render_complete",this.c)};z.u(vL,z.wl);vL.prototype.yC=$K.C();vL.prototype.h=function(){vL.b.h.call(this);this.stop();delete this.M;delete this.ha;wL(this);z.Bl(this);this.qj&&(this.qj.p(),delete this.qj)};vL.prototype.kz=function(){this.stop();wL(this);vL.b.kz.call(this)};z.mg.main.Ih.ia(vL);})(fyre.conv);
