var VariScroll,VARISCROLL_MODE_DEFAULT="variScrollModeDefault",VARISCROLL_CONTAINER_CLASS="variscroll-container",VARISCROLL_ACTIVE_CLASS="variscroll-active",VARISCROLL_PAUSED_CLASS="variscroll-paused",VARISCROLL_DESTROYED_CLASS="variscroll-destroyed",VARISCROLL_OPTIONS_DATA="variscroll-options",VARISCROLL_REF_DATA="variscroll-ref";(function(a,b,c,d){"use strict";VariScroll=function(e,f){this.options=f;this.$innerContainer=e;this.$outerContainer=null;this.$document=a(c);this.$window=a(b);this.metadata=this.$innerContainer.data===d?{}:this.$innerContainer.data(VARISCROLL_OPTIONS_DATA);this.isPaused=!1;this.innerContainerTopPos=0;this.outerContainerHeight=0;this.prevDocumentScrollTop=0;this.rollbackOffs=0};VariScroll.prototype={defaults:{logger:null,mode:VARISCROLL_MODE_DEFAULT,ratio:.3,headerHeight:0,isManual:!1,isRollbackEnabled:!0,isOuterContainerHeightChangeEnabled:!0,outerContainer:null,footerElement:null},init:function(){this.config=a.extend({},this.defaults,this.options,this.metadata);if(this.config.mode!==VARISCROLL_MODE_DEFAULT&&!this.config.isRollbackEnabled)throw"VariScroll: Invalid mode ("+ this.config.mode+")";this.config.logger!==null&&this.config.logger("VariScroll: Initializing with these settings:",this.config);if(this.config.isManual){if(this.config.outerContainer)this.$outerContainer=this.config.outerContainer;else{this.$outerContainer=this.$innerContainer.parent();this.config.outerContainer="{parent}"}
if(this.$outerContainer.length===0){this.config.outerContainer="";throw"VariScroll: Outer container does not exist"}
this.$innerContainer.css({position:"fixed",top:this.innerContainerTopPos,width:this.$innerContainer.width()});this.$outerContainer.removeClass(VARISCROLL_DESTROYED_CLASS+" "+ VARISCROLL_PAUSED_CLASS).addClass(VARISCROLL_ACTIVE_CLASS)}else{var b=a("<div class='"+ VARISCROLL_CONTAINER_CLASS+"' />").css({position:"fixed",top:this.innerContainerTopPos,width:this.$innerContainer.width()});this.$innerContainer.wrapInner(b).removeClass(VARISCROLL_DESTROYED_CLASS+" "+ VARISCROLL_PAUSED_CLASS).addClass(VARISCROLL_ACTIVE_CLASS);this.$outerContainer=this.$innerContainer;this.$innerContainer=this.$outerContainer.find(".variscroll-container")}
this.config.isOuterContainerHeightChangeEnabled&&this.$outerContainer.css("height","1px");var c=function(a){a.data.refresh()};this.$window.on("scroll.variscroll",this,c).on("resize.variscroll",this,c);this.refresh();return this},destroy:function(){this.config.logger&&this.config.logger("VariScroll: destroy");this.$window.unbind(".variscroll");if(this.config.isManual){this.$innerContainer.css({position:"",top:"",width:""});this.$outerContainer.addClass(VARISCROLL_DESTROYED_CLASS).removeClass(VARISCROLL_ACTIVE_CLASS+" "+ VARISCROLL_PAUSED_CLASS).removeData(VARISCROLL_OPTIONS_DATA+" "+ VARISCROLL_REF_DATA)}else this.$innerContainer.html(this.$inner.html()).addClass(VARISCROLL_DESTROYED_CLASS).removeClass(VARISCROLL_ACTIVE_CLASS+" "+ VARISCROLL_PAUSED_CLASS).removeData(VARISCROLL_OPTIONS_DATA+" "+ VARISCROLL_REF_DATA);this.config.isOuterContainerHeightChangeEnabled&&this.$outerContainer.css("height","");return this},refresh:function(){if(!this.isPaused){var a=0,b=0,c=this.$window.height(),d=this.$document.height(),e=this.$document.scrollTop(),f=this.prevDocumentScrollTop- e,g=this.$innerContainer.height(),h=this.$outerContainer.offset().top,i=!1;if(e>d- c){e=d- c;this.rollbackOffs=0}
if(e<0){e=0;this.rollbackOffs=0}
if(this.config.mode===VARISCROLL_MODE_DEFAULT)if(g>=d){a=h- e;b=g;i=!0}else if(e<h- this.config.headerHeight){a=h- e;b=g;this.rollbackOffs=0}else if(g<c- this.config.headerHeight){e>d- g&&(a=d- e- g);a+=this.config.headerHeight;b=g- h+ e+ a}else if((g- c)/this.config.ratio+c>=d){a=h-e;a+g<c&&(a=c-g);b=g;if(this.config.isRollbackEnabled){a>=this.config.headerHeight?this.rollbackOffs=0:f>this.config.headerHeight?a-this.rollbackOffs<0&&a+g===c&&(this.rollbackOffs-=f):this.rollbackOffs<0&&a+g===c&&(this.rollbackOffs-=f);a-=this.rollbackOffs;a>this.config.headerHeight&&(a=this.config.headerHeight);g>c&&a<c-g&&(a=c-g);b=g-h+e+a}}else{var j=0;if(g>c){j=-e+h-this.config.headerHeight;a=j*this.config.ratio+this.config.headerHeight}else{a=this.config.headerHeight;this.rollbackOffs=0}b=e+g-h;if(a<c-g){a=j=c-g;j=0;if(e>d-c){j+=h-e+g-c;a+=h-e+(g-c)/this.config.ratio
}
b=g- h+ e+ a}
if(this.config.isRollbackEnabled){var k=this.rollbackOffs*this.config.ratio;a>=this.config.headerHeight?this.rollbackOffs=0:f>0?a- k<this.config.headerHeight&&j===0&&a+ g===c&&(this.rollbackOffs-=f):this.rollbackOffs<0&&j===0&&(this.rollbackOffs-=f);a-=k;a>this.config.headerHeight&&(a=this.config.headerHeight);g>c&&a<c- g&&(a=c- g);b=g- h+ e+ a}}
if(this.config.footerElement!==null){var l=a+ g,m=this.config.footerElement.offset().top- e;m<l&&(a-=l- m)}
b<e+ c&&(b=e+ c);this.rollbackOffs>0&&(this.rollbackOffs=0);if(a!==this.innerContainerTopPos){this.$innerContainer.css("top",Math.round(a));this.innerContainerTopPos=a}
if(this.config.isOuterContainerHeightChangeEnabled&&b!==this.outerContainerHeight||i){this.$outerContainer.css("height",Math.round(b));this.outerContainerHeight=b}
this.prevDocumentScrollTop=e}
return this},pause:function(){if(this.isPaused)this.config.logger&&this.config.logger("VariScroll: won't pause, already paused");else{this.config.logger&&this.config.logger("VariScroll: pause");this.isPaused=!0;this.$innerContainer.addClass(VARISCROLL_PAUSED_CLASS)}},resume:function(){if(this.isPaused){this.config.logger&&this.config.logger("VariScroll: resume");this.isPaused=!1;this.$innerContainer.removeClass(VARISCROLL_PAUSED_CLASS)}else this.config.logger&&this.config.logger("VariScroll: won't resume, already running")},setRatio:function(a){this.config.logger&&this.config.logger("VariScroll: changing ratio to "+ a);this.config.ratio=a;this.refresh()}};a.fn.variScroll=function(b){var c=this.data(),d;c&&(d=c.data?c.data.variscrollRef:c.variscrollRef);return d?d:this.each(function(){var c=new VariScroll(a(this),b);a.data(this,VARISCROLL_REF_DATA,c);c.init()})};VariScroll.defaults=VariScroll.prototype.defaults})(jQuery,window,document);